// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortfolioApp.Infrastructure.Persistence;

#nullable disable

namespace PortfolioApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260623194703_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortfolioApp.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("asset_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("quote_currency");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("IX_Assets_Ticker");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("PortfolioApp.Domain.Entities.DemoSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_DemoSessions_ExpiresAt");

                    b.HasIndex("PortfolioId")
                        .IsUnique();

                    b.ToTable("DemoSessions", (string)null);
                });

            modelBuilder.Entity("PortfolioApp.Domain.Entities.FxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("from_currency");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("rate");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("to_currency");

                    b.HasKey("Id");

                    b.HasIndex("FromCurrency", "ToCurrency", "RecordedAt")
                        .HasDatabaseName("IX_FxRates_FromTo_RecordedAt");

                    b.ToTable("FxRates", (string)null);
                });

            modelBuilder.Entity("PortfolioApp.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Portfolios_UserId");

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("PortfolioApp.Domain.Entities.PriceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("price");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "RecordedAt")
                        .HasDatabaseName("IX_PriceSnapshots_AssetId_RecordedAt");

                    b.ToTable("PriceSnapshots", (string)null);
                });

            modelBuilder.Entity("PortfolioApp.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("price_per_unit");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("quantity");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("IX_Transactions_AssetId");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("IX_Transactions_PortfolioId");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("IX_Transactions_TransactionDate");

                    b.HasIndex("PortfolioId", "AssetId")
                        .HasDatabaseName("IX_Transactions_PortfolioId_AssetId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("PortfolioApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDemoTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_demo_template");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email")
                        .HasFilter("email IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PortfolioApp.Domain.Entities.DemoSession", b =>
                {
                    b.HasOne("PortfolioApp.Domain.Entities.Portfolio", "Portfolio")
                        .WithOne("DemoSession")
                        .HasForeignKey("PortfolioApp.Domain.Entities.DemoSession", "PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("PortfolioApp.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("PortfolioApp.Domain.Entities.User", "User")
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PortfolioApp.Domain.Entities.PriceSnapshot", b =>
                {
                    b.HasOne("PortfolioApp.Domain.Entities.Asset", "Asset")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PortfolioApp.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("PortfolioApp.Domain.Entities.Asset", "Asset")
                        .WithMany("Transactions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortfolioApp.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Transactions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("PortfolioApp.Domain.Entities.Asset", b =>
                {
                    b.Navigation("PriceSnapshots");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PortfolioApp.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("DemoSession");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PortfolioApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
